language: node_js
node_js:
    - 13

services:
    - docker
#building
script:
    - docker --version # print the version for logging

    # build images
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker build -t udagram-api-user ./udagram-api-user
    - docker build -t reverseproxy ./udagram-reverseproxy
    - docker build -t udagram-frontend ./udagram-frontend

    # Add tags to images
    - docker tag udagram-api-feed "$DOCKER_USERNAME/udagram-api-feed:v1"
    - docker tag udagram-api-user "$DOCKER_USERNAME/udagram-api-user:v1"
    - docker tag reverseproxy "$DOCKER_USERNAME/reverseproxy:v1"
    - docker tag udagram-frontend "$DOCKER_USERNAME/udagram-frontend:v1"

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # push images
    - docker push "$DOCKER_USERNAME/udagram-api-feed:v1"
    - docker push "$DOCKER_USERNAME/udagram-api-user:v1"
    - docker push "$DOCKER_USERNAME/reverseproxy:v1"
    - docker push "$DOCKER_USERNAME/udagram-frontend:v1"   - docker push kemiamb/reverseproxy:v2
